version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./graphql-server/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  graphql:
    build: ./graphql-server
    ports:
      - "5678:5678"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: mydb

volumes:
  postgres_data: