services:
  express:
    build: .
    ports:
      - "3030:3030"
    depends_on:
      - graphql
    volumes:
      - ./data:/app/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  graphql:
    build: ../pokenext-graphql
    ports:
      - "5678:5678"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/mydb
    volumes:
    - ./data:/app/data


volumes:
  mongo_data: