# Use Node.js LTS image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci
# Copy the rest of the source code
COPY ./src ./src

# Expose the port your Express server uses (e.g., 3000)
EXPOSE 3000

# Start the server
CMD ["npm", "run", "start"]